# Test 5: Regex
print("=== Regex ===")
print(regex_match("[0-9]+", "123"))
print(regex_match("[0-9]+", "abc"))
print(regex_search("[0-9]+", "abc123def456"))
print(regex_search("[a-z]+", "123abc"))
print(regex_replace("[0-9]+", "NUM", "abc123def456"))
print(regex_replace("a", "b", "aaa"))
print(regex_match("^[a-z]+$", "hello"))
print(regex_match("^\\d{3}-\\d{4}$", "123-4567"))
print(regex_search("\\w+", "hello world"))
print(regex_replace("\\s+", "-", "hello   world"))