var s = "hello world"
print(upper(s))
print(lower(s))
print(strip("  hello  "))
print(split("a,b,c", ","))
print(join(["a", "b", "c"], "-"))
print(replace("hello world", "world", "ipp"))
print(starts_with("hello", "he"))
print(ends_with("hello", "lo"))
print(find("hello", "l"))
print(contains("hello", "ell"))
print(count("hello llo llo", "llo"))
print(strip("   "))
print(replace_all("aaa", "a", "b"))
print(substring("hello", 1, 3))
print(char_at("hello", 1))
print(ascii("A"))
print(from_ascii(65))