# Test 2: String Methods
var s = "  Hello World  "

print("=== String Methods ===")
print(upper(s))
print(lower(s))
print(strip(s))
print(replace("hello world", "world", "ipp"))
print(starts_with("hello", "he"))
print(ends_with("hello", "lo"))
print(find("hello", "l"))
print(contains("hello", "ell"))
print(count("hello llo llo", "llo"))
print(split("a,b,c", ","))
print(join(["a", "b", "c"], "-"))
print(substring("hello", 1, 3))
print(char_at("hello", 1))
print(ascii("A"))
print(from_ascii(65))
print(replace_all("aaa", "a", "b"))
print(index_of("hello", "l"))
print(split_lines("line1\nline2\nline3"))
print(startswith("hello", "hel"))
print(endswith("hello", "lo"))