(module
  (memory 1 256)
  (table 1 funcref)
  (func $print (import "env" "print") (param i32))
  (func $print_f64 (import "env" "print_f64") (param f64))
  (func $print_str (import "env" "print_str") (param i32))
  (func $add (param ) (result i32)
  (i32.const 10)
  (i32.const 20)
  (i32.add)
  (return)
)
  (export "add" (func $add))
  (data (i32.const 0) "Hello, World!\00")
)